services:
    sdz_blog.antispam:
        class: Sdz\BlogBundle\Antispam\SdzAntispam
        arguments: [@mailer, %locale%, 3]
#    sdzblog.validator.antiflood:
#        class: Sdz\BlogBundle\Validator\AntiFloodValidator
#        arguments: [@request, @doctrine.orm.entity_manager]
#        tags:
#            - { name: validator.constraint_validator, alias: sdzblog_antiflood }
#    sdz_blog.example:
#        class: Sdz\BlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
